/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
//package raft
//
//import com.sun.org.apache.xerces.internal.dom.NodeImpl
//import kotlin.test.Test
//import kotlin.test.assertNotNull
//
//class AppTest {
//    @Test
//    fun testAppHasAGreeting() {
////        val classUnderTest = Node()
////        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
//}
